version: '2'
services:
  apollo:
    image: idoop/docker-apollo:latest
    container_name: apollo
    hostname: apollo

    # 目前只能用host模式,否则将出现504错误,如果想改端口,参考下方修改端口的环境变量
    network_mode: "host"

    # 如果需要查看日志,挂载容器中的/opt路径出来即可.
    volumes:
      - ./logs:/opt/logs

    environment:
      # 开启Portal,默认端口: 8070
      PORTAL_DB: jdbc:mysql://ugiant.f3322.net:23306/ApolloPortalDB?characterEncoding=utf8
      PORTAL_DB_USER: root
      PORTAL_DB_PWD: javadev
      PORTAL_PORT: 8070

      # 开启dev环境, 默认端口: config 8080, admin 8090
      DEV_DB: jdbc:mysql://xxxx:23306/ApolloConfigDBDev?characterEncoding=utf8
      DEV_DB_USER: root
      DEV_DB_PWD: javadev
      CONFIG_DEV_PORT: 8080
      ADMIN_DEV_PORT: 8090

      # 指定远程dev地址
      DEV_URL: http://127.0.0.1:8080