version: '3'
services:
  gitlab:
    image: 'fjcanyue/gitlab-ce-zh:latest'
    restart: always
    hostname: '192.168.0.107'
    environment:
      TZ: 'Asia/Shanghai'
      COMPOSE_PROJECT_NAME: 'gitlab-server'
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://192.168.0.107:10080'
        gitlab_rails['gitlab_shell_ssh_port'] = 2222
        unicorn['port'] = 8888
        nginx['listen_port'] = 10080

    ports:
      - '10080:10080'
      - '10443:443'
      - '10022:22'
    volumes:
      - /opt/gitlab/config:/etc/gitlab
      - /opt/gitlab/data:/var/opt/gitlab
      - /opt/gitlab/logs:/var/log/gitlab
