version: '2'

services:
  redis:
    image: 'bitnami/redis:latest'
    ports:
      - '6379:6379'
    environment:
      - REDIS_PASSWORD=123456
    volumes:
          - '/Users/qingyang/Desktop/aoki/docker/volume/redis:/bitnami'